[project]
target_repo_path = ""
hierarchy_path = ".project_hierarchy.json"
markdown_docs_path = "markdown_docs"
ignore_list = []
language = "Chinese"

[chat_completion_kwargs]
model = "gpt-3.5-turbo"
temperature = 0.2
request_timeout = 60
base_url = "https://api.openai.com"
